name: rahhid

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget
      - name: download sdk
        run: wget https://downloads.openwrt.org/releases/21.02.3/targets/mvebu/cortexa9/openwrt-sdk-21.02.3-mvebu-cortexa9_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
      - name: extract sdk
        run: tar xf openwrt-sdk-21.02.3-mvebu-cortexa9_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
      - name: cd sdk
        run: cd openwrt-sdk-21.02.3-mvebu-cortexa9_gcc-8.4.0_musl_eabi.Linux-x86_64
      - name: setup feeds
        run: |
          cp feeds.conf.default feeds.conf
          echo 'src-git burghardt https://github.com/burghardt/openwrt-feed.git' >> feeds.conf
      - name: feeds update
        run: ./scripts/feeds update -a
      - name: feeds install
        run: ./scripts/feeds install -a -p burghardt
      - name: compile
        run: make package/rahhid/compile
