name: openwrt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  openwrt:
    strategy:
      matrix:
        version: [
          "24.10.2-bcm47xx-generic_gcc-13.3.0_musl",
          "23.05.6-x86-generic_gcc-12.3.0_musl",
          "22.03.4-armvirt-64_gcc-11.2.0_musl",
        ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget
      - name: download sdk
        run: |
          release=$(cut -f1 -d- <<< ${{ matrix.version }})
          target=$(cut -f2 -d- <<< ${{ matrix.version }})
          variant=$(cut -f3 -d- <<< ${{ matrix.version }} | cut -f1 -d_)
          wget https://downloads.openwrt.org/releases/${release}/targets/${target}/${variant}/openwrt-sdk-${{ matrix.version }}.Linux-x86_64.tar.xz || \
          wget https://downloads.openwrt.org/releases/${release}/targets/${target}/${variant}/openwrt-sdk-${{ matrix.version }}.Linux-x86_64.tar.zst
      - name: extract sdk
        run: |
          tar xf openwrt-sdk-${{ matrix.version }}.Linux-x86_64.tar.xz || \
          tar xf openwrt-sdk-${{ matrix.version }}.Linux-x86_64.tar.zst
      - name: setup feeds
        run: |
          cd openwrt-sdk-${{ matrix.version }}.Linux-x86_64
          cp feeds.conf.default feeds.conf
          sed -Ei 's\https://git.openwrt.org/(project|feed|openwrt)\https://github.com/openwrt\g' feeds.conf
          echo 'src-git burghardt https://github.com/burghardt/openwrt-feed.git' >> feeds.conf
      - name: feeds update
        run: |
          cd openwrt-sdk-${{ matrix.version }}.Linux-x86_64
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p burghardt
      - name: compile
        run: |
          cd openwrt-sdk-${{ matrix.version }}.Linux-x86_64
          make defconfig
          make package/rahhid/compile
